remote_theme: christianezeani/panthera-jekyll
menu:
  - text: References
    link: /References
    icon: ""

  - text: Final Project
    link: /FinalProject
    icon: ""
  - text: Home Page
    link: /index
    icon: ""
