remote_theme: christianezeani/panthera-jekyll
menu:
  - text: Home Page
    link: /index
    icon: ""
  - text: References
    link: /References
    icon: ""
  - text: Final Project
    link: /FinalProject
    icon: ""
  - text: Project Management
    link: /ProjectManagement
    icon: ""
  - text: Photoshop Tutorial
    link: /Photoshop1
    icon: ""
  - text: Fusion-Personalised Keychain
    link: /Fusion1
    icon: ""
  - text: Fusion-Chess Piece
    link: /Fusion2
    icon: ""
